use axum::extract::State;
use axum::http::StatusCode;
use hashbrown::HashMap;
use serde_json::Map as JsonMap;

use crate::{
    api::{ApiJson, Error, HttpResult},
    app::AppState,
};

use super::{
    super::{
        channel_auth::{AuthorizedChannel, authorize_channel_by_password},
        entity_input::{
            EntityId, ExtensionObjectRef, MetadataEntries, NormalizedImageUrls, NormalizedTags,
            ObjectPatchRef, OptionalText,
        },
        message::{OpId, ResolvedSemanticId, SemanticScope, dispatch_entity_notification},
    },
    EventCloseRequest, EventCreateRequest, EventIntent, EventProfile, EventRouteAction,
    EventSummary, EventUpdateRequest,
    validation::{normalize_event_message, normalize_event_severity, normalize_event_status},
};

async fn event_to_channel_with_action(
    state: AppState,
    authorized_channel: AuthorizedChannel,
    payload: EventIntent,
    route_action: EventRouteAction,
) -> HttpResult {
    let requested_state = route_action.requested_state();
    if payload.channel_id.trim().is_empty() {
        return Err(Error::validation("channel id must not be empty"));
    }
    let channel_id = authorized_channel.channel_id;
    let channel_scope = authorized_channel.channel_scope.clone();

    let op_id = OpId::resolve(payload.op_id.as_deref())?.into_inner();
    let thing_id = payload
        .thing_id
        .as_deref()
        .map(|raw| EntityId::parse(raw, "thing_id").map(EntityId::into_inner))
        .transpose()?;
    if route_action == EventRouteAction::Create
        && payload
            .event_id
            .as_deref()
            .is_some_and(|value| !value.trim().is_empty())
    {
        return Err(Error::validation(
            "event_id is generated by gateway on /event/create",
        ));
    }
    let resolved_event_id = match route_action {
        EventRouteAction::Create => {
            ResolvedSemanticId::resolve_create(
                &state,
                SemanticScope::semantic_create_key(
                    &channel_scope,
                    "event",
                    thing_id.as_deref(),
                    &OpId::parse(&op_id)?,
                )
                .as_str(),
            )
            .await?
        }
        EventRouteAction::Update | EventRouteAction::Close => ResolvedSemanticId {
            semantic_id: {
                let raw = payload
                    .event_id
                    .as_deref()
                    .ok_or_else(|| Error::validation("event_id is required"))?;
                EntityId::parse(raw, "event_id")?.into_inner()
            },
        },
    };
    let event_id = resolved_event_id.semantic_id;
    let normalized_tags = payload
        .payload
        .tags
        .as_deref()
        .map(|tags| NormalizedTags::parse(tags, "tags").map(NormalizedTags::into_inner))
        .transpose()?;
    let normalized_severity = payload
        .payload
        .severity
        .as_deref()
        .map(normalize_event_severity)
        .transpose()?;
    let normalized_status = payload
        .payload
        .status
        .as_deref()
        .map(normalize_event_status)
        .transpose()?;
    let normalized_message = payload
        .payload
        .message
        .as_deref()
        .map(normalize_event_message)
        .transpose()?;
    let normalized_images =
        NormalizedImageUrls::parse(&payload.payload.images, "images")?.into_inner();
    let normalized_description = OptionalText::normalize(payload.payload.description.as_deref());

    ExtensionObjectRef::new(&payload.payload.attrs, "attrs").validate()?;
    MetadataEntries::new(&payload.payload.metadata).validate()?;
    route_action.validate_temporal_fields(payload.payload.started_at, payload.payload.ended_at)?;
    route_action.validate_required_fields(
        payload.payload.title.as_deref(),
        &normalized_status,
        &normalized_message,
        &normalized_severity,
    )?;

    let mut custom_data = HashMap::with_capacity(1);
    if !payload.payload.metadata.is_empty() {
        custom_data.insert(
            "metadata".to_string(),
            MetadataEntries::new(&payload.payload.metadata).encode()?,
        );
    }

    let event_time = payload
        .payload
        .event_time
        .ok_or_else(|| Error::validation_code("event_time is required", "event_time_required"))?;

    let mut merged_profile = EventProfile::default();
    if let Some(title) = payload.payload.title.as_ref() {
        merged_profile.title = Some(title.clone());
    }
    if let Some(description) = normalized_description.as_ref() {
        merged_profile.description = Some(description.clone());
    }
    if let Some(status) = normalized_status.as_ref() {
        merged_profile.status = Some(status.clone());
    }
    if let Some(message) = normalized_message.as_ref() {
        merged_profile.message = Some(message.clone());
    }
    if let Some(severity) = normalized_severity.as_ref() {
        merged_profile.severity = Some(severity.clone());
    }
    if let Some(tags) = normalized_tags {
        merged_profile.tags = tags;
    }
    merged_profile.started_at =
        route_action.resolve_started_at(payload.payload.started_at, None, event_time);
    merged_profile.ended_at =
        route_action.resolve_ended_at(payload.payload.ended_at, None, event_time);
    for value in &normalized_images {
        if !merged_profile.images.iter().any(|item| item == value) {
            merged_profile.images.push(value.clone());
        }
    }
    let merged_profile = if merged_profile.is_empty() {
        None
    } else {
        Some(merged_profile)
    };
    let resolved_profile_json = merged_profile
        .as_ref()
        .map(|profile| {
            serde_json::to_string(profile).map_err(|err| Error::validation(err.to_string()))
        })
        .transpose()?;

    let effective_state = requested_state;
    let resolved_thing_id = thing_id.clone();

    let mut final_attrs = JsonMap::new();
    ObjectPatchRef::new(&payload.payload.attrs).apply_to(&mut final_attrs);
    let attrs_json_in = if payload.payload.attrs.is_empty() {
        None
    } else {
        Some(
            serde_json::to_string(&payload.payload.attrs)
                .map_err(|err| Error::validation(err.to_string()))?,
        )
    };

    let notification_title = payload.payload.title.clone().or_else(|| {
        merged_profile
            .as_ref()
            .and_then(|profile| profile.title.clone())
    });
    let notification_body = normalized_message
        .clone()
        .or(normalized_description.clone());

    let dispatch_summary = {
        let mut extra = HashMap::with_capacity(7);
        extra.insert("event_id".to_string(), event_id.clone());
        extra.insert(
            "event_state".to_string(),
            effective_state.as_api_str().to_string(),
        );
        extra.insert("occurred_at".to_string(), event_time.to_string());
        extra.insert("event_time".to_string(), event_time.to_string());
        if let Some(value) = resolved_thing_id.as_deref() {
            extra.insert("thing_id".to_string(), value.to_string());
        }
        if let Some(value) = resolved_profile_json.as_deref() {
            extra.insert("event_profile_json".to_string(), value.to_string());
        }
        if let Some(value) = attrs_json_in.as_deref() {
            extra.insert("event_attrs_json".to_string(), value.to_string());
        }

        Some(
            dispatch_entity_notification(
                &state,
                channel_id,
                op_id.clone(),
                event_time,
                notification_title.clone(),
                notification_body.clone(),
                None,
                None,
                custom_data.clone(),
                "event",
                &event_id,
                extra,
            )
            .await?,
        )
    };

    let mut response = EventSummary {
        channel_id: channel_scope,
        op_id,
        event_id,
        thing_id: resolved_thing_id,
        accepted: true,
    };
    if let Some(summary) = dispatch_summary.as_ref()
        && let Some(error_message) = summary.failure_error_message()
    {
        response.accepted = false;
        return Ok(
            crate::api::StatusResponse::err_with_data(error_message, response)
                .with_status(StatusCode::SERVICE_UNAVAILABLE),
        );
    }
    Ok(crate::api::ok(response))
}

pub(crate) async fn event_create_to_channel(
    State(state): State<AppState>,
    ApiJson(payload): ApiJson<EventCreateRequest>,
) -> HttpResult {
    let password = payload
        .common
        .password
        .as_deref()
        .ok_or_else(|| Error::validation("password is required"))?;
    let authorized_channel =
        authorize_channel_by_password(&state, &payload.common.channel_id, password).await?;
    event_to_channel_with_action(
        state,
        authorized_channel,
        EventIntent::from_create(payload),
        EventRouteAction::Create,
    )
    .await
}

pub(crate) async fn event_create_authorized(
    state: &AppState,
    payload: EventCreateRequest,
    authorized_channel: AuthorizedChannel,
) -> HttpResult {
    event_to_channel_with_action(
        state.clone(),
        authorized_channel,
        EventIntent::from_create(payload),
        EventRouteAction::Create,
    )
    .await
}

pub(crate) async fn event_update_to_channel(
    State(state): State<AppState>,
    ApiJson(payload): ApiJson<EventUpdateRequest>,
) -> HttpResult {
    let password = payload
        .common
        .password
        .as_deref()
        .ok_or_else(|| Error::validation("password is required"))?;
    let authorized_channel =
        authorize_channel_by_password(&state, &payload.common.channel_id, password).await?;
    event_to_channel_with_action(
        state,
        authorized_channel,
        EventIntent::from_update(payload),
        EventRouteAction::Update,
    )
    .await
}

pub(crate) async fn event_update_authorized(
    state: &AppState,
    payload: EventUpdateRequest,
    authorized_channel: AuthorizedChannel,
) -> HttpResult {
    event_to_channel_with_action(
        state.clone(),
        authorized_channel,
        EventIntent::from_update(payload),
        EventRouteAction::Update,
    )
    .await
}

pub(crate) async fn event_close_to_channel(
    State(state): State<AppState>,
    ApiJson(payload): ApiJson<EventCloseRequest>,
) -> HttpResult {
    let password = payload
        .common
        .password
        .as_deref()
        .ok_or_else(|| Error::validation("password is required"))?;
    let authorized_channel =
        authorize_channel_by_password(&state, &payload.common.channel_id, password).await?;
    event_to_channel_with_action(
        state,
        authorized_channel,
        EventIntent::from_close(payload),
        EventRouteAction::Close,
    )
    .await
}

pub(crate) async fn event_close_authorized(
    state: &AppState,
    payload: EventCloseRequest,
    authorized_channel: AuthorizedChannel,
) -> HttpResult {
    event_to_channel_with_action(
        state.clone(),
        authorized_channel,
        EventIntent::from_close(payload),
        EventRouteAction::Close,
    )
    .await
}
