use axum::extract::State;
use axum::http::StatusCode;
use hashbrown::HashMap;
use serde_json::Map as JsonMap;

use crate::{
    api::{ApiJson, Error, HttpResult},
    app::AppState,
    storage::ThingState,
};

use super::{
    super::{
        channel_auth::{AuthorizedChannel, authorize_channel_by_password},
        entity_input::{
            EntityId, ExtensionObjectRef, MetadataEntries, NormalizedImageUrls, NormalizedTags,
            OptionalText, OptionalUrl,
        },
        message::{OpId, ResolvedSemanticId, SemanticScope, dispatch_entity_notification},
    },
    ThingArchiveRequest, ThingCreateRequest, ThingDeleteRequest, ThingIntent, ThingProfile,
    ThingRouteAction, ThingSummary, ThingUpdateRequest,
    helpers::{ExternalIdPatchRef, thing_state_api_text, validate_manufacturer_attrs},
};

async fn thing_to_channel_with_action(
    state: AppState,
    authorized_channel: AuthorizedChannel,
    payload: ThingIntent,
    route_action: ThingRouteAction,
) -> HttpResult {
    if payload.channel_id.trim().is_empty() {
        return Err(Error::validation("channel id must not be empty"));
    }
    let channel_id = authorized_channel.channel_id;
    let channel_scope = authorized_channel.channel_scope.clone();

    let op_id = OpId::resolve(payload.op_id.as_deref())?.into_inner();
    if route_action == ThingRouteAction::Create
        && payload
            .thing_id
            .as_deref()
            .is_some_and(|value| !value.trim().is_empty())
    {
        return Err(Error::validation(
            "thing_id is generated by gateway on /thing/create",
        ));
    }
    let resolved_thing_id = match route_action {
        ThingRouteAction::Create => {
            ResolvedSemanticId::resolve_create(
                &state,
                SemanticScope::semantic_create_key(
                    &channel_scope,
                    "thing",
                    None,
                    &OpId::parse(&op_id)?,
                )
                .as_str(),
            )
            .await?
        }
        ThingRouteAction::Update | ThingRouteAction::Archive | ThingRouteAction::Delete => {
            ResolvedSemanticId {
                semantic_id: {
                    let raw = payload
                        .thing_id
                        .as_deref()
                        .ok_or_else(|| Error::validation("thing_id is required"))?;
                    EntityId::parse(raw, "thing_id")?.into_inner()
                },
            }
        }
    };
    let thing_id = resolved_thing_id.semantic_id;

    let normalized_tags = payload
        .payload
        .mutable
        .tags
        .as_deref()
        .map(|tags| NormalizedTags::parse(tags, "tags").map(NormalizedTags::into_inner))
        .transpose()?;
    let normalized_images =
        NormalizedImageUrls::parse(&payload.payload.mutable.images, "images")?.into_inner();
    let normalized_primary_image = OptionalUrl::normalize(
        payload.payload.mutable.primary_image.as_deref(),
        "primary_image",
    )?;
    let normalized_ciphertext =
        OptionalText::normalize(payload.payload.mutable.ciphertext.as_deref());
    let normalized_description =
        OptionalText::normalize(payload.payload.mutable.description.as_deref());
    ExtensionObjectRef::new(&payload.payload.mutable.attrs, "attrs").validate()?;
    validate_manufacturer_attrs(&payload.payload.mutable.attrs)?;
    ExternalIdPatchRef::new(&payload.payload.mutable.external_ids).validate()?;
    let normalized_location = super::ThingLocation::normalize_patch(
        payload.payload.mutable.location_type.as_deref(),
        payload.payload.mutable.location_value.as_deref(),
    )?;
    MetadataEntries::new(&payload.payload.mutable.metadata).validate()?;

    let observed_at =
        payload.payload.mutable.observed_at.ok_or_else(|| {
            Error::validation_code("observed_at is required", "observed_at_required")
        })?;

    let mut custom_data = HashMap::with_capacity(2);
    if !payload.payload.mutable.metadata.is_empty() {
        custom_data.insert(
            "metadata".to_string(),
            MetadataEntries::new(&payload.payload.mutable.metadata).encode()?,
        );
    }
    if let Some(ciphertext) = normalized_ciphertext.as_ref() {
        custom_data.insert("ciphertext".to_string(), ciphertext.clone());
    }

    let mut merged_profile = ThingProfile::default();
    if let Some(title) = payload.payload.mutable.title.clone() {
        merged_profile.title = Some(title);
    }
    if let Some(description) = normalized_description.clone() {
        merged_profile.description = Some(description);
    }
    if let Some(tags) = normalized_tags {
        merged_profile.tags = tags;
    }
    let resolved_created_at = match route_action {
        ThingRouteAction::Update | ThingRouteAction::Archive | ThingRouteAction::Delete => {
            if payload.payload.created_at.is_some() {
                return Err(Error::validation(
                    "created_at is only allowed on /thing/create",
                ));
            }
            None
        }
        ThingRouteAction::Create => payload.payload.created_at.or(Some(observed_at)),
    };
    merged_profile.created_at = resolved_created_at;
    if let Some(image) = normalized_primary_image {
        merged_profile.primary_image = Some(image);
    }
    if !normalized_images.is_empty() {
        for image in &normalized_images {
            merged_profile.push_unique_image(image);
        }
    }

    let resolved_state = route_action.resolved_state();
    merged_profile.state = Some(thing_state_api_text(resolved_state).to_string());
    merged_profile.deleted_at = if resolved_state == ThingState::Decommissioned {
        payload
            .payload
            .deleted_at
            .or(merged_profile.deleted_at)
            .or(Some(observed_at))
    } else {
        None
    };

    if !payload.payload.mutable.external_ids.is_empty() {
        ExternalIdPatchRef::new(&payload.payload.mutable.external_ids)
            .apply_to(&mut merged_profile.external_ids)?;
    }
    if let Some(location) = normalized_location {
        merged_profile.location = Some(location);
    }

    let merged_profile = if merged_profile.is_empty() {
        None
    } else {
        Some(merged_profile)
    };
    let resolved_profile_json = merged_profile
        .as_ref()
        .map(|profile| {
            serde_json::to_string(profile).map_err(|err| Error::validation(err.to_string()))
        })
        .transpose()?;

    let mut final_attrs = JsonMap::new();
    for (key, value) in &payload.payload.mutable.attrs {
        if value.is_null() {
            final_attrs.remove(key);
        } else {
            final_attrs.insert(key.clone(), value.clone());
        }
    }
    let final_attrs_json =
        serde_json::to_string(&final_attrs).map_err(|err| Error::validation(err.to_string()))?;

    let (notification_title, notification_body) = route_action.build_notification_content(
        &payload,
        merged_profile.as_ref(),
        normalized_description,
    );

    let dispatch_summary = {
        let mut extra = HashMap::with_capacity(4);
        extra.insert("occurred_at".to_string(), observed_at.to_string());
        extra.insert("thing_id".to_string(), thing_id.clone());
        extra.insert("thing_attrs_json".to_string(), final_attrs_json.clone());
        if let Some(value) = resolved_profile_json.as_ref() {
            extra.insert("thing_profile_json".to_string(), value.clone());
        }

        Some(
            dispatch_entity_notification(
                &state,
                channel_id,
                op_id.clone(),
                observed_at,
                notification_title,
                notification_body,
                None,
                None,
                custom_data,
                "thing",
                &thing_id,
                extra,
            )
            .await?,
        )
    };

    let mut response = ThingSummary {
        channel_id: channel_scope,
        op_id,
        thing_id,
        accepted: true,
    };
    if let Some(summary) = dispatch_summary.as_ref()
        && let Some(error_message) = summary.failure_error_message()
    {
        response.accepted = false;
        return Ok(
            crate::api::StatusResponse::err_with_data(error_message, response)
                .with_status(StatusCode::SERVICE_UNAVAILABLE),
        );
    }
    Ok(crate::api::ok(response))
}

pub(crate) async fn thing_create_to_channel(
    State(state): State<AppState>,
    ApiJson(payload): ApiJson<ThingCreateRequest>,
) -> HttpResult {
    let password = payload
        .common
        .password
        .as_deref()
        .ok_or_else(|| Error::validation("password is required"))?;
    let authorized_channel =
        authorize_channel_by_password(&state, &payload.common.channel_id, password).await?;
    thing_to_channel_with_action(
        state,
        authorized_channel,
        ThingIntent::from_create(payload),
        ThingRouteAction::Create,
    )
    .await
}

pub(crate) async fn thing_create_authorized(
    state: &AppState,
    payload: ThingCreateRequest,
    authorized_channel: AuthorizedChannel,
) -> HttpResult {
    thing_to_channel_with_action(
        state.clone(),
        authorized_channel,
        ThingIntent::from_create(payload),
        ThingRouteAction::Create,
    )
    .await
}

pub(crate) async fn thing_update_to_channel(
    State(state): State<AppState>,
    ApiJson(payload): ApiJson<ThingUpdateRequest>,
) -> HttpResult {
    let password = payload
        .common
        .password
        .as_deref()
        .ok_or_else(|| Error::validation("password is required"))?;
    let authorized_channel =
        authorize_channel_by_password(&state, &payload.common.channel_id, password).await?;
    thing_to_channel_with_action(
        state,
        authorized_channel,
        ThingIntent::from_update(payload),
        ThingRouteAction::Update,
    )
    .await
}

pub(crate) async fn thing_update_authorized(
    state: &AppState,
    payload: ThingUpdateRequest,
    authorized_channel: AuthorizedChannel,
) -> HttpResult {
    thing_to_channel_with_action(
        state.clone(),
        authorized_channel,
        ThingIntent::from_update(payload),
        ThingRouteAction::Update,
    )
    .await
}

pub(crate) async fn thing_archive_to_channel(
    State(state): State<AppState>,
    ApiJson(payload): ApiJson<ThingArchiveRequest>,
) -> HttpResult {
    let password = payload
        .common
        .password
        .as_deref()
        .ok_or_else(|| Error::validation("password is required"))?;
    let authorized_channel =
        authorize_channel_by_password(&state, &payload.common.channel_id, password).await?;
    thing_to_channel_with_action(
        state,
        authorized_channel,
        ThingIntent::from_archive(payload),
        ThingRouteAction::Archive,
    )
    .await
}

pub(crate) async fn thing_archive_authorized(
    state: &AppState,
    payload: ThingArchiveRequest,
    authorized_channel: AuthorizedChannel,
) -> HttpResult {
    thing_to_channel_with_action(
        state.clone(),
        authorized_channel,
        ThingIntent::from_archive(payload),
        ThingRouteAction::Archive,
    )
    .await
}

pub(crate) async fn thing_delete_to_channel(
    State(state): State<AppState>,
    ApiJson(payload): ApiJson<ThingDeleteRequest>,
) -> HttpResult {
    let password = payload
        .common
        .password
        .as_deref()
        .ok_or_else(|| Error::validation("password is required"))?;
    let authorized_channel =
        authorize_channel_by_password(&state, &payload.common.channel_id, password).await?;
    thing_to_channel_with_action(
        state,
        authorized_channel,
        ThingIntent::from_delete(payload),
        ThingRouteAction::Delete,
    )
    .await
}

pub(crate) async fn thing_delete_authorized(
    state: &AppState,
    payload: ThingDeleteRequest,
    authorized_channel: AuthorizedChannel,
) -> HttpResult {
    thing_to_channel_with_action(
        state.clone(),
        authorized_channel,
        ThingIntent::from_delete(payload),
        ThingRouteAction::Delete,
    )
    .await
}
