use axum::extract::State;
use serde::{Deserialize, Deserializer};
use serde_json::{Map as JsonMap, Value};

use crate::{
    api::{
        ApiJson, Error, HttpResult, deserialize_empty_as_none, deserialize_unix_ts_millis_lenient,
        validate_channel_password,
    },
    app::AppState,
    delivery_core::source::IngressSource,
};

use super::entity_input::{EntityId, MetadataEntries};

mod compat;
mod counters;
#[path = "dispatch/mod.rs"]
mod dispatch;
mod ids;

pub(crate) use compat::{
    compat_bark_v1_body, compat_bark_v1_title_body, compat_bark_v2_push, compat_ntfy_get,
    compat_ntfy_post, compat_ntfy_put, compat_serverchan_get, compat_serverchan_post,
    message_to_channel_get,
};
pub(crate) use dispatch::dispatch_entity_notification;
pub(crate) use ids::OpId;

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct MessageIntent {
    pub channel_id: String,
    pub password: String,
    #[serde(default, deserialize_with = "deserialize_empty_as_none")]
    pub op_id: Option<String>,
    #[serde(
        default,
        rename = "message_id",
        deserialize_with = "reject_forbidden_message_id"
    )]
    _message_id: Option<serde_json::Value>,
    pub thing_id: Option<String>,
    #[serde(default, deserialize_with = "deserialize_unix_ts_millis_lenient")]
    pub occurred_at: Option<i64>,
    pub title: String,
    pub body: Option<String>,
    pub severity: Option<String>,
    #[serde(default, deserialize_with = "deserialize_unix_ts_millis_lenient")]
    pub ttl: Option<i64>,
    pub url: Option<String>,
    #[serde(default)]
    pub images: Vec<String>,
    pub ciphertext: Option<String>,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default, deserialize_with = "deserialize_metadata_map")]
    pub metadata: JsonMap<String, Value>,
}

fn reject_forbidden_message_id<'de, D>(
    deserializer: D,
) -> Result<Option<serde_json::Value>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let _ = serde::de::IgnoredAny::deserialize(deserializer)?;
    Err(serde::de::Error::custom(
        "message_id is generated by the gateway",
    ))
}

impl MessageIntent {
    pub(crate) fn validate_payload(&self) -> Result<(), Error> {
        if self.channel_id.trim().is_empty() {
            return Err(Error::validation_code(
                "channel id must not be empty",
                "channel_id_required",
            ));
        }
        validate_channel_password(&self.password)?;
        if let Some(op_id) = self.op_id.as_deref() {
            OpId::parse(op_id)?;
        }
        if self.title.trim().is_empty() {
            return Err(Error::validation_code(
                "title must not be empty",
                "title_required",
            ));
        }
        MetadataEntries::new(&self.metadata).validate()?;
        Ok(())
    }
}

pub(super) fn deserialize_metadata_map<'de, D>(
    deserializer: D,
) -> Result<JsonMap<String, Value>, D::Error>
where
    D: Deserializer<'de>,
{
    let raw = Option::<Value>::deserialize(deserializer)?;
    let Some(raw) = raw else {
        return Ok(JsonMap::new());
    };
    parse_metadata_map_value(raw).map_err(serde::de::Error::custom)
}

pub(super) fn parse_metadata_map_value(raw: Value) -> Result<JsonMap<String, Value>, String> {
    MetadataEntries::parse_value(raw)
}

pub(crate) async fn message_to_channel(
    State(state): State<AppState>,
    ApiJson(payload): ApiJson<MessageIntent>,
) -> HttpResult {
    let span = tracing::info_span!("gateway.api.message.request");
    let fut = async move {
        let scoped_thing_id = payload
            .thing_id
            .as_deref()
            .map(|raw| EntityId::parse(raw, "thing_id").map(EntityId::into_inner))
            .transpose()?;
        dispatch_message_intent(&state, payload, scoped_thing_id).await
    };
    tracing::Instrument::instrument(fut, span)
        .await
        .inspect_err(|err: &Error| {
            ::tracing::event!(
                target: "gateway.trace_event",
                ::tracing::Level::WARN,
                event = "message.route_failed",
                error = %(err.to_string())
            );
        })
}

pub(super) async fn dispatch_message_intent(
    state: &AppState,
    payload: MessageIntent,
    scoped_thing_id: Option<String>,
) -> HttpResult {
    payload.validate_payload()?;
    let response_thing_id = scoped_thing_id;
    let outcome = crate::services::send_message(
        state,
        crate::services::MessageSendCommand {
            channel_id: payload.channel_id,
            password: payload.password,
            op_id: payload.op_id,
            thing_id: response_thing_id.clone(),
            occurred_at: payload.occurred_at,
            title: payload.title,
            body: payload.body,
            severity: payload.severity,
            ttl: payload.ttl,
            url: payload.url,
            images: payload.images,
            ciphertext: payload.ciphertext,
            tags: payload.tags,
            metadata: payload.metadata,
            source: IngressSource::HttpMessage,
        },
    )
    .await?;
    let summary = outcome.summary;
    let ack = super::send_ack::SendAck {
        op_id: summary.op_id.clone(),
        message_id: Some(outcome.message_id),
        event_id: None,
        thing_id: None,
    };
    Ok(ack.into_http_response())
}

#[cfg(test)]
mod tests;
